services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - E:\h_lab\n8n:/mnt/hostdrive
    environment:
      - N8N_PORT=5678
      - NODE_ENV=production

volumes:
  n8n_data:
    external: true