global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Node Exporter metrics
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'windows_exporter'
    static_configs:
      - targets: ['host.docker.internal:9182']
  - job_name: 'go_ecom_system_metrics'
    static_configs:
      - targets: ['host.docker.internal:8081']
  - job_name: 'node_system_metrics'
    static_configs:
      - targets: ['host.docker.internal:2113']
  - job_name: 'cAdivsor'
    static_configs:
      - targets: ['host.docker.internal:8085']